public class MultiplyTwoNumbers {

    public static void main(String[] args) {

       Double first = 1.5f;
        Double second = 2.0f;

        Double product = first * second;

        System.out.println("The product is: " + product);
    }
}
Welcome to Multiplication World???? Hiiii
Hi User, Welcome to Windows Dashboard"[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D"Wel
